backend:
  name: github
  repo:  saladbowl77/blog
locale: 'ja' #日本語対応
local_backend: true # ローカルサーバーに対応させる設定

media_folder: "static/images"

public_folder: "images/"

collections:
  - label: "Blog"
    name: "blog"
    folder: "content/blog"
    path: "{{year}}/{{month}}/{{slug}}"
    preview_path: "blog/{{year}}/{{month}}/{{slug}}"
    create: true
    slug: '{{fields.slug}}'
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "url名", name: "slug", widget: "string"}
      - {label: "公開日", name: "date", widget: "datetime"}
      - {label: "PNG画像",name: "imgUrl", widget: "image", default: "/images/default.png", media_folder: "/static/images/", public_folder : "/images/"}
      - {label: "あらすじ", name: "description", widget: "string"}
      - {label: "タグ", name: "tags", widget: "list"}
      - {label: "本文", name: "body", widget: "text"}
      - {label: "TwitterCard", name: "card", widget: "select", options: ["summary", "summary_large_image"]}
